### PR TITLE
Convert Visual Studio Solution to CMake

### PR DESCRIPTION
**Pull request by Chronophylos**
CMake builds a `.sln` and MVSC compiles it into a Library.
I also added checks for the current platform. For example if we're on Windows we add some more flags and include `windows.h`

I moved the source files into `src/` to cleanup the repository a bit.

### CODE REVIEW

**Comment by Sparker95** [comment]
Thanks, I will try to learn how to use CMAKE. Did you try to build it for linux already?

**Comment by Chronophylos** [comment]
No, since it uses `dllmain` wich does not exist on Linux

**Comment by Sparker95** [comment]
As I know, for linux we must build libraries with `.so` extension.

**Comment by xoorath** [comment]
Hey @Chronophylos , I think it this PR of yours covers a lot of the same ground as my new PR for adding Linux support. 

https://github.com/Vindicta-Team/FileXT/pull/7

If you have improvements to suggest, let me know!

**Comment by Chronophylos** [comment]
The PR looks good to me

**Pull request closed without merging**
